# Generated by Django 5.2.3 on 2025-07-18 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_payments_link_payments_session_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='payment_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='payment status'),
        ),
    ]
