# Generated by Django 5.2.3 on 2025-06-18 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the course', max_length=255, verbose_name='Course Name')),
                ('preview', models.ImageField(blank=True, help_text='Upload a preview image for the course. Optional.', null=True, upload_to='lms/course_previews/', verbose_name='Course Preview')),
                ('description', models.TextField(blank=True, help_text='Enter a brief description of the course', null=True, verbose_name='Course Description')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the lesson', max_length=255, verbose_name='Lesson Name')),
                ('description', models.TextField(blank=True, help_text='Enter a brief description of the lesson. Optional.', null=True, verbose_name='Lesson Description')),
                ('preview', models.ImageField(blank=True, help_text='Upload a preview image for the lesson. Optional.', null=True, upload_to='lms/lesson_previews/', verbose_name='Lesson Preview')),
                ('video_url', models.URLField(blank=True, help_text='Enter the URL of the lesson video. Optional.', null=True, verbose_name='Video URL')),
                ('course', models.ForeignKey(blank=True, help_text='Select the course this lesson belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='lms.course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
                'ordering': ['name'],
            },
        ),
    ]
