# Generated by Django 5.2.3 on 2025-07-22 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_coursesubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='The date and time when the course was last updated', null=True, verbose_name='Updated At'),
        ),
    ]
